Question.create!([
  {quiz_id: 1, number: 2, ask: "Which game is this map from?\r\n\r\n<img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Risk_game_map_fixed.png/1000px-Risk_game_map_fixed.png\" class=\"img-fluid\">", answer: "Risk", form_type: "select_menu", config: {"options"=>["Monopoly", "Diplomacy", "Risk", "Quest"]}},
  {quiz_id: 1, number: 3, ask: "## Which is the **lowliest** chess piece?\r\n![](https://cf.geekdo-images.com/opengraph/img/R3tD3P1aOdBq-XlIZDu_OZCk9nU=/fit-in/1200x630/pic260745.jpg)\r\n\r\nHint: there are 8 of these per side\r\n", answer: "Pawn", form_type: "multiple_choice", config: {"options"=>["King", "Queen", "Bishop", "Knight", "Rook", "Pawn"], "button"=>{"class"=>"btn btn-outline-dark btn-lg"}}},
  {quiz_id: 1, number: 1, ask: "## In which year between 1930 and 1940 was Monopoly released?\r\n\r\n![](https://c1.staticflickr.com/1/2/1583381_8ba0a9f12f_b.jpg)", answer: "1935", form_type: "input_field", config: {"input"=>{"type"=>"number", "max"=>1940, "min"=>1930}}},
  {quiz_id: 2, number: 1, ask: "What is jersey number is **Lionel Messi** wearing?\r\n\r\n![](https://upload.wikimedia.org/wikipedia/commons/a/aa/ECUADOR_VS_ARGENTINA_%2836956136633%29.jpg)", answer: "10", form_type: "input_field", config: {"input"=>{"type"=>"number"}}},
  {quiz_id: 2, number: 2, ask: "### Who is this?\r\n![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlIiMthwLOenH7jMylcsMRUTuctC0oi7OvrA5ovK9bx1Yv4_-F7g)", answer: "Ronaldo", form_type: "input_field", config: nil},
  {quiz_id: 3, number: 1, ask: "![](https://35b7f1d7d0790b02114c-1b8897185d70b198c119e1d2b7efd8a2.ssl.cf1.rackcdn.com/team_photo/3466410/original/7badf668-a5f1-42ee-962d-c92cf51d6f5b.jpg)\r\n## What is the four-letter name of this team?", answer: "HABS", form_type: "input_field", config: {"input"=>{"size"=>4}}},
  {quiz_id: 3, number: 2, ask: "## Which is the best club in the CDSFA?\r\n\r\n![](/test_images/HPWFC.jpg)\r\n**HPWFC**\r\n\r\n![](/test_images/BTFC.jpg)\r\n**BTFC**\r\n\r\n![](/test_images/MRDFC.jpg)\r\n**MRDFC**\r\n\r\n", answer: "HPWFC", form_type: "multiple_choice", config: {"options"=>["HPWFC", "BTFC", "MRDFC"], "buttons"=>[{"class"=>"btn btn-primary"}, {"class"=>"btn btn-warning"}, {"class"=>"btn btn-danger"}]}},
  {quiz_id: 4, number: 1, ask: "![](/test_images/italy.jpg)\r\n\r\nWho is reported to have said?\r\n\r\n> I couldn't settle in Italy. It was like living in a foreign country.", answer: "Denis Law", form_type: "multiple_choice", config: {"options"=>["Denis Law", "Ian Rush", "John Charles", "Graham Souness"], "button"=>{"class"=>"btn btn-outline-primary"}}},
  {quiz_id: 4, number: 2, ask: "Can you tell who this famous EPL player is, just from a photo of his football boot?\r\n\r\n![](/test_images/pinkdotboot.png)", answer: "Lionel Messi", form_type: "multiple_choice", config: {"options"=>["Lionel Messi", "Sergio Aguero", "Daniel Strurridge", "Anthony Martial"]}},
  {quiz_id: 4, number: 3, ask: "![](/test_images/west-ham-v-west-brom.jpg)\r\n\r\nDuring the 2017/18 EPL season, **West Bromwich Albion** and **West Ham United** collectively received 3 red cards.\r\n\r\nHow many yellow cards did they collectively receive?", answer: "146", form_type: "multiple_choice", config: {"options"=>[146, 55, 45, 22]}},
  {quiz_id: 5, number: 1, ask: nil, answer: nil, form_type: "input_field", config: nil}
])
