## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per environment.
authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: ou=groups,dc=engines,dc=internal
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - cn=admins,ou=groups,dc=engines,dc=internal
    - cn=users,ou=groups,dc=engines,dc=internal
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["moreMembers", "cn=users,ou=groups,dc=engines,dc=internal"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin
  ## Requires config.ldap_check_attributes_presence in devise.rb to be true
  ## Can have multiple attributes set to true or false to check presence, all must match all to be authorized
  require_attribute_presence:
    mail: true
    telephoneNumber: true
    serviceAccount: false

## Environment

# config.ldap = {
#   host: ENV['DEVISE_LDAP_HOST'] || 'ldap',
#   port: ENV['DEVISE_LDAP_PORT'] || 636,
#   admin_username: ENV['DEVISE_LDAP_ADMIN_USERNAME'] || 'admin',
#   admin_password: ENV['DEVISE_LDAP_ADMIN_PASSWORD']
# }


development:
  host: <%= ENV.fetch("DEVISE_LDAP_HOST") { "ldap" } %>
  port: <%= ENV.fetch("DEVISE_LDAP_PORT") { "389" } %>
  attribute: cn
  base: ou=people,dc=engines,dc=internal
  admin_user: cn=<%= ENV.fetch("DEVISE_LDAP_ADMIN_USERNAME") { "admin" } %>,dc=engines,dc=internal
  admin_password: <%= ENV.fetch("DEVISE_LDAP_ADMIN_PASSWORD") { "password" } %>
  ssl: false
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=engines,dc=internal
  admin_user: cn=admin,dc=engines,dc=internal
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: <%= ENV.fetch("DEVISE_LDAP_HOST") { "ldap" } %>
  port: <%= ENV.fetch("DEVISE_LDAP_PORT") { "636" } %>
  attribute: cn
  base: ou=people,dc=engines,dc=internal
  admin_user: cn=<%= ENV.fetch("DEVISE_LDAP_ADMIN_USERNAME") { "admin" } %>,dc=engines,dc=internal
  admin_password: <%= ENV.fetch("DEVISE_LDAP_ADMIN_PASSWORD") { nil } %>
  ssl: start_tls
  # <<: *AUTHORIZATIONS
